services:
  - docker

before_install:
- docker pull docker:dind

script:
- cd $TRAVIS_BUILD_DIR/images
- docker build -t mailcow-dind mailcow-dind
- docker run -e HOSTNAME='mailplace.com' -e CRON_BACKUP='* * * * * *' -e TIMEZONE='UTC' -e API_KEY=abcd1234 -e API_IPS='127.0.0.1,127.0.0.1' -v /home/travis/dind:/var/lib/docker -v /home/travis/mailcow:/mailcow -v /home/travis/mailcow-backup:/mailcow-backup -v /lib/modules:/lib/modules:ro --name mailcow-dind --privileged -d mailcow-dind
- docker logs mailcow-dind -f &
- sleep 4m
- docker stop mailcow-dind

after_script:
- docker tag mailcow-dind quay.io/promaethius/mailcow-dind:$TRAVIS_BRANCH
- mkdir -p ~/.docker
- |
  cat > ~/.docker/config.json << EOF
  {
    "auths": {
      "quay.io": {
        "auth": "$TOKEN"
      }
    }
  }
  EOF
- docker push quay.io/promaethius/mailcow-dind:$TRAVIS_BRANCH
