services:
  - docker

before_install:
- docker pull docker:dind

script:
- cd images
- docker build -t mailcow-dind mailcow-dind
- docker run -e HOSTNAME=example.com -e CRON_BACKUP='* * * * * *' -e TIMEZONE=PDT -v /home/travis/dind:/var/lib/docker -v /home/travis/mailcow:/mailcow -v /home/travis/mailcow-backup:/mailcow-backup --name mailcow-dind --privileged mailcow-dind
