services:
  - docker

before_install:
- docker pull docker:dind

script:
- cd images
- docker build -t mailcow-dind mailcow-dind
- docker run -e HOSTNAME='example.com' -e CRON_BACKUP='* * * * * *' -e TIMEZONE='PDT' -v /home/travis/dind:/var/lib/docker -v /home/travis/mailcow:/mailcow -v /home/travis/mailcow-backup:/mailcow-backup --name mailcow-dind --privileged -d mailcow-dind
- docker logs mailcow-dind -f &
- sleep 4m
- docker stop mailcow-dind

after_script:
- docker tag mailcow-dind quay.io/promaethius/mailcow-dind
- mkdir -p ~/.docker
- |
  cat > ~/.docker/config.json << EOF
  {
    "auths": {
      "quay.io": {
        "auth": "$TOKEN"
      }
    }
  }
- docker push quay.io/promaethius/mailcow-dind
