services:
  - docker

before_install:
- docker pull docker:dind

script:
- cd $TRAVIS_BUILD_DIR/images
- docker build -t mailcow-dind mailcow-dind
- bash $TRAVIS_BUILD_DIR/e2e/main.sh

after_script:
- docker tag mailcow-dind quay.io/promaethius/mailcow-dind:$TRAVIS_BRANCH
- mkdir -p ~/.docker
- |
  cat > ~/.docker/config.json << EOF
  {
    "auths": {
      "quay.io": {
        "auth": "$TOKEN"
      }
    }
  }
  EOF
- docker push quay.io/promaethius/mailcow-dind:$TRAVIS_BRANCH
