apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailcow-dind
  labels:
    app: mailcow-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailcow-dind
  template:
    metadata:
      labels:
        app: mailcow-dind
    spec:
      containers:
      - name: mailcow-dind
        image: quay.io/Promaethius/mailcow-dind
        restart: Always
        env:
          - name: HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: mailcow-dind
                key: hostname
          - name: TIMEZONE
            valueFrom:
              configMapKeyRef:
                name: mailcow-dind
                key: timezone
          - name: CRON_BACKUP
            valueFrom:
              configMapKeyRef:
                name: mailcow-dind
                key: cronBackup
        volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-persistent
        - mountPath: /mailcow
          name: mailcow-persistent
        - mountPath: /mailcow-backup
          name: mailcow-backup
        - mountPath: /lib/modules
          name: lib-modules
        securityContext:
          capabilities:
            privileged: true
      volumes:
      - name: dind-persistent
        persistentVolumeClaim:
          claimName: dind-persistent
      - name: mailcow-persistent
        persistentVolumeClaim:
          claimName: mailcow-persistent
      - name: mailcow-backup
        persistentVolumeClaim:
          claimName: mailcow-backup
      - name: lib-modules
        hostPath: 
          path: /lib/modules
