kind: Service
apiVersion: v1
metadata:
  name: mailcow-dind
spec:
  selector:
    app: mailcow-dind
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: smtp
    protocol: TCP
    port: 25
    targetPort: 25
  - name: smtps
    protocol: TCP
    port: 465
    targetPort: 465
  - name: submission
    protocol: TCP
    port: 587
    targetPort: 587
  - name: imap
    protocol: TCP
    port: 143
    targetPort: 143
  - name: imaps
    protocol: TCP
    port: 993
    targetPort: 993
  - name: pop
    protocol: TCP
    port: 110
    targetPort: 110
  - name: pops
    protocol: TCP
    port: 995
    targetPort: 995
  - name: sieve
    protocol: TCP
    port: 4190
    targetPort: 4190
