apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-persistent
  labels:
    app: mailcow-dind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailcow-persistent
  labels:
    app: mailcow-dind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailcow-backup
  labels:
    app: mailcow-dind
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
